<!--
This file is part of JavaSMT,
an API wrapper for a collection of SMT solvers:
https://github.com/sosy-lab/java-smt

SPDX-FileCopyrightText: 2025 Dirk Beyer <https://www.sosy-lab.org>

SPDX-License-Identifier: Apache-2.0
-->

<ivy-module version="2.0">
    <info organisation="${project.organization}" module="${project.module}"/>

    <configurations>
        <conf name="test" extends="runtime" visibility="private"/>
        <conf name="runtime"/>
    </configurations>

    <dependencies>
        <!-- JavaSMT -->
        <dependency org="org.sosy_lab" name="java-smt" rev="6.0.0-148-gba08f432a" conf="runtime->runtime-x64,runtime-arm64">
            <exclude org="org.sosy_lab" module="javasmt-solver-optimathsat"/>
            <exclude org="org.sosy_lab" module="javasmt-solver-mathsat"/>
            <exclude org="org.sosy_lab" module="javasmt-solver-cvc4"/>
        </dependency>
        <dependency org="org.sosy_lab" name="javasmt-solver-mathsat" rev="5.6.11" conf="runtime->solver-mathsat" />
        <dependency org="org.sosy_lab" name="javasmt-solver-cvc4" rev="1.8-prerelease-2020-06-24-g7825d8f28" conf="runtime->solver-cvc4" />

        <!-- JUnit6 -->
        <dependency org="org.junit.jupiter" name="junit-jupiter-api" rev="6.1.0" conf="test->default"/>
        <dependency org="org.junit.jupiter" name="junit-jupiter-params" rev="6.1.0" conf="test->default"/>
        <dependency org="org.junit.jupiter" name="junit-jupiter-engine" rev="6.1.0" conf="test->default"/>

        <!-- JUnit6 console launcher -->
        <dependency org="org.junit.platform" name="junit-platform-console" rev="6.1.0" conf="test->default"/>
    </dependencies>
</ivy-module>
