# This file is part of JavaSMT,
# an API wrapper for a collection of SMT solvers:
# https://github.com/sosy-lab/java-smt
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push

jobs:
  linux:
    name: Linux
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 21 ]
        arch: [ x64, arm64 ]
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          architecture: ${{ matrix.arch }}

      - name: Shared Ivy Cache
        uses: actions/cache@v5
        with:
          path: ~/.ivy2
          # We use a unique key for each run to ensure the cache is updated if needed,
          # while restoring from the most recent "ivy-shared-" cache.
          key: ivy-shared-${{ github.run_id }}
          restore-keys: |
            ivy-shared-
          enableCrossOsArchive: true

      - name: Build Ivy project
        run: |
          cd doc/Example-Ivy-Project
          ant compile

      - name: Show solver table
        run: |
          cd doc/Example-Ivy-Project
          ant run

      - name: Run tests
        run: |
          cd doc/Example-Ivy-Project
          ant test
