# This file is part of JavaSMT,
# an API wrapper for a collection of SMT solvers:
# https://github.com/sosy-lab/java-smt
#
# SPDX-FileCopyrightText: 2026 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push

jobs:
  ivy:
    name: Ivy Example Project
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 21 ]
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-2025, windows-11-arm, macos-26-intel, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Shared Ivy Cache
        uses: actions/cache@v5
        with:
          path: $HOME/.ivy2
          # We use a unique key for each run to ensure the cache is updated if needed,
          # while restoring from the most recent "ivy-shared-" cache.
          key: ivy-shared-${{ github.run_id }}
          restore-keys: |
            ivy-shared-
          enableCrossOsArchive: true

      - name: Build Ivy project
        run: |
          cd doc/Example-Ivy-Project
          ant compile

      - name: Show solver table
        run: |
          cd doc/Example-Ivy-Project
          ant run
        env:
          LD_PRELOAD: /usr/lib/${{ matrix.os == 'ubuntu-24.04-arm' && 'aarch64-linux-gnu' || 'x86_64-linux-gnu' }}/libstdc++.so.6

      - name: Run tests
        run: |
          cd doc/Example-Ivy-Project
          ant test
        env:
          LD_PRELOAD: /usr/lib/${{ matrix.os == 'ubuntu-24.04-arm' && 'aarch64-linux-gnu' || 'x86_64-linux-gnu' }}/libstdc++.so.6

      - name: Upload test report
        uses: actions/upload-artifact@v7
        with:
          path: doc/Example-Ivy-Project/build/test-report/html/junit-noframes.html
          archive: false
